# GW2 API
GW2_API_BASE_URL = "https://api.guildwars2.com/v2"
GW2_API_ITEMS_URL = GW2_API_BASE_URL + "/items"
GW2_API_RECIPE_SEARCH_URL = GW2_API_BASE_URL + "/recipes"
GW2_API_RECIPE_URL = GW2_API_BASE_URL + "/recipes/search"
GW2_API_TP_LIST_URL = GW2_API_BASE_URL + "/listings"


# Rate
DEFAULT_BURST = 300
DEFAULT_REFILL_RATE = 5.0
MAX_IDS_PER_REQUEST = 200